run:
	g++ sub_main.cpp mosquitto.cpp time_mosq.cpp utf8_mosq.cpp net_mosq.cpp packet_mosq.cpp messages_mosq.cpp property_mosq.cpp connect.cpp packet_datatypes.cpp log_printf.cpp util_mosq.cpp send_connect.cpp send_subscribe.cpp send_unsubscribe.cpp send_publish.cpp sub_actions.cpp sub_util_topic.cpp sub_callbacks.cpp handle_functions.cpp read_handle.cpp loop.cpp send_mosq.cpp thread_mosq.cpp send_disconnect.cpp -o sub -lmosquitto -pthread -g 

