run:
	g++ pub_main.cpp actions.cpp net_mosq.cpp time_mosq.cpp connect.cpp  packet_datatypes.cpp read_handle.cpp utf8_mosq.cpp handle_functions.cpp packet_mosq.cpp send_connect.cpp util_mosq.cpp loop.cpp property_mosq.cpp send_disconnect.cpp util_topic.cpp send_mosq.cpp messages_mosq.cpp send_publish.cpp mosquitto.cpp thread_mosq.cpp -o pub -lmosquitto -pthread -g 

